export const SEED_BUSINESSES = [
  {
    id: 'sm-01',
    name: 'Remedy Wellness Studio',
    description: "Santa Monica's premier biohacking studio offering cutting-edge recovery and longevity therapies. Walk in or book online.",
    address: '1437 7th St',
    city: 'Santa Monica',
    state: 'CA',
    zip: '90401',
    phone: '(310) 555-0182',
    website: 'https://remedywellness.com',
    latitude: 34.0195,
    longitude: -118.4912,
    status: 'approved',
    hours: {
      mon: '7:00 AM – 8:00 PM',
      tue: '7:00 AM – 8:00 PM',
      wed: '7:00 AM – 8:00 PM',
      thu: '7:00 AM – 8:00 PM',
      fri: '7:00 AM – 8:00 PM',
      sat: '8:00 AM – 6:00 PM',
      sun: '9:00 AM – 4:00 PM',
    },
    walkIn: 'welcome',
    modalities: [
      { name: 'Red Light Therapy',    category: 'modality' },
      { name: 'PEMF Therapy',         category: 'modality' },
      { name: 'Cold Plunge',          category: 'modality' },
      { name: 'Sauna',                category: 'modality' },
      { name: 'Infrared Sauna',       category: 'modality' },
      { name: 'Compression Therapy',  category: 'modality' },
      { name: 'Joovv Grand 3.0',      category: 'device'   },
      { name: 'Pulse PEMF XL Pro',    category: 'device'   },
      { name: 'Clearlight Sanctuary Series', category: 'device' },
      { name: 'NormaTec',             category: 'device'   },
      { name: 'NAD+ IV',              category: 'compound' },
      { name: 'BPC-157',              category: 'compound' },
      { name: 'Glutathione IV',       category: 'compound' },
      { name: 'Myers Cocktail IV',    category: 'compound' },
    ],
  },
  {
    id: 'bw-01',
    name: 'Apex Human Performance',
    description: "Brentwood's elite performance and recovery center. Trusted by pro athletes, executives, and anyone serious about optimizing their health.",
    address: '11677 San Vicente Blvd',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90049',
    phone: '(310) 555-0247',
    website: 'https://apexhumanperformance.com',
    latitude: 34.0494,
    longitude: -118.4734,
    status: 'approved',
    hours: {
      mon: '6:00 AM – 9:00 PM',
      tue: '6:00 AM – 9:00 PM',
      wed: '6:00 AM – 9:00 PM',
      thu: '6:00 AM – 9:00 PM',
      fri: '6:00 AM – 9:00 PM',
      sat: '7:00 AM – 7:00 PM',
      sun: '8:00 AM – 5:00 PM',
    },
    walkIn: 'appointment',
    modalities: [
      { name: 'Hyperbaric Oxygen',  category: 'modality' },
      { name: 'IV Therapy',         category: 'modality' },
      { name: 'Peptide Therapy',    category: 'modality' },
      { name: 'Cryotherapy',        category: 'modality' },
      { name: 'Red Light Therapy',  category: 'modality' },
      { name: 'PEMF Therapy',       category: 'modality' },
      { name: 'Hard Shell Chamber', category: 'device'   },
      { name: 'CryoStar Chamber',   category: 'device'   },
      { name: 'Joovv Solo 3.0',     category: 'device'   },
      { name: 'Pulse PEMF XL Pro',  category: 'device'   },
      { name: 'BPC-157',            category: 'compound' },
      { name: 'TB-500',             category: 'compound' },
      { name: 'Sermorelin',         category: 'compound' },
      { name: 'Ipamorelin',         category: 'compound' },
      { name: 'NAD+ IV',            category: 'compound' },
      { name: 'Glutathione IV',     category: 'compound' },
      { name: 'Testosterone',       category: 'compound' },
      { name: 'HGH',                category: 'compound' },
    ],
  },
  {
    id: 'sm-02',
    name: 'The Float Collective',
    description: "Venice and Santa Monica's most loved float and sound healing sanctuary. Disconnect from the noise and reconnect with yourself.",
    address: '3301 Ocean Park Blvd',
    city: 'Santa Monica',
    state: 'CA',
    zip: '90405',
    phone: '(310) 555-0391',
    website: 'https://thefloatcollective.com',
    latitude: 34.0005,
    longitude: -118.4571,
    status: 'approved',
    hours: {
      mon: '8:00 AM – 10:00 PM',
      tue: '8:00 AM – 10:00 PM',
      wed: '8:00 AM – 10:00 PM',
      thu: '8:00 AM – 10:00 PM',
      fri: '8:00 AM – 10:00 PM',
      sat: '8:00 AM – 10:00 PM',
      sun: '8:00 AM – 10:00 PM',
    },
    walkIn: 'welcome',
    modalities: [
      { name: 'Float Tank',         category: 'modality' },
      { name: 'Sound Healing',      category: 'modality' },
      { name: 'Sauna',              category: 'modality' },
      { name: 'Infrared Sauna',     category: 'modality' },
      { name: 'Breathwork',         category: 'modality' },
      { name: 'Cold Plunge',        category: 'modality' },
      { name: 'Float Pod Pro',      category: 'device'   },
      { name: 'Clearlight Sanctuary Series', category: 'device' },
    ],
  },
  {
    id: 'bh-01',
    name: 'Vitality IV & Peptide Clinic',
    description: "Beverly Hills' most comprehensive peptide and IV therapy clinic. Medical-grade protocols administered by licensed practitioners.",
    address: '8920 Wilshire Blvd',
    city: 'Beverly Hills',
    state: 'CA',
    zip: '90211',
    phone: '(310) 555-0558',
    website: 'https://vitalityivbh.com',
    latitude: 34.0736,
    longitude: -118.3976,
    status: 'approved',
    hours: {
      mon: '9:00 AM – 6:00 PM',
      tue: '9:00 AM – 6:00 PM',
      wed: '9:00 AM – 6:00 PM',
      thu: '9:00 AM – 6:00 PM',
      fri: '9:00 AM – 6:00 PM',
      sat: '10:00 AM – 4:00 PM',
      sun: 'Closed',
    },
    walkIn: 'appointment',
    modalities: [
      { name: 'IV Therapy',           category: 'modality' },
      { name: 'Peptide Therapy',      category: 'modality' },
      { name: 'EBOO (Extracorporeal Blood Ozonation & Oxygenation)', category: 'modality' },
      { name: 'Ozone Therapy',        category: 'modality' },
      { name: 'PRP Therapy',          category: 'modality' },
      { name: 'Stem Cell Therapy',    category: 'modality' },
      { name: 'NAD+ IV',              category: 'compound' },
      { name: 'BPC-157',              category: 'compound' },
      { name: 'TB-500',               category: 'compound' },
      { name: 'Sermorelin',           category: 'compound' },
      { name: 'Ipamorelin',           category: 'compound' },
      { name: 'CJC-1295',             category: 'compound' },
      { name: 'Thymosin Alpha-1',     category: 'compound' },
      { name: 'GHK-Cu',               category: 'compound' },
      { name: 'Glutathione IV',       category: 'compound' },
      { name: 'Vitamin C (High-Dose) IV', category: 'compound' },
      { name: 'Myers Cocktail IV',    category: 'compound' },
      { name: 'Testosterone',         category: 'compound' },
      { name: 'Semaglutide',          category: 'compound' },
      { name: 'Tirzepatide',          category: 'compound' },
      { name: 'HGH',                  category: 'compound' },
    ],
  },
];
